### ISSUE TITLE
Первое задание!

### ISSUE THREAD

**Issue by mgulimonov** [fireet/hello_world#1]
Отлично выглядит!

Теперь в качестве факультатива и для быстрого освовения, измени это приложение так, чтобы оно желало

Доброй ночи
Доброго утра
Доброго дня
Доброго вечера

в зависимости от времени суток. Это будет хорошее упражнение

**Comment by mgulimonov** [comment]
Олично. Теперь представь, что языков может быть много. 
У тебя должна быть возможность при старте программы выбрать на каком языке тебя поприветствовать.

К примеру:
$ python3 hello_world.py ru

При этом код должен поддерживать возможность легко добавлять новые языки.
Как ты изменишь программу в этом случае?

**Comment by mgulimonov** [comment]
@fireet  Кстати "сообщение" по-английски
message а не massage =)

**Comment by fireet** [comment]
Полность переписал программу. ну хоть язык спрашивает

**Comment by fireet** [comment]
Сделал приветствие без перебора значенийю(я уверен есть способ проще, но я до него пока видимо не дошёл)
доступен выбор языка из консоли
