### ISSUE TITLE
Убрать дублирование кода

### ISSUE THREAD

**Issue by mgulimonov** [fireet/hello_world#3]
1. В 2х функциях которые ты написал код очень сильно дублируется.
Представь что тебе нужно добавить еще 5 языков... С текущей реализацией тебе придется 5 раз скопипастить одну и ту же функцию. Дублирование кода нужно устранить.

2. Решение с использование слоаваря (dict) верное, но можно упростить:
В сутка 24 часа. Если поделить текущее время суток на некое число нацело мы будет получать для разных часов одинаковый результат. К примеру

13 часов / 8 = 1
14 часов / 8 = 1
15 часов / 8 = 1
16 часов / 8 = 2

Подумай как это можно использовать чтобы упростить словарь который ты используешь.

3. Так же обрати внимение что при добавлении нового языка тебе придется добавлять еще условия if в теле приложения. Как этого можно избежать?

**Comment by fireet** [comment]
Убрано дублирование кода, сокразен словарь. 
Проверка условий пока что не готова

**Comment by fireet** [comment]
исправлена проверка условий)
