### ISSUE TITLE
Добавление новых языков в файл.

### ISSUE THREAD

**Issue by mgulimonov** [fireet/hello_world#6]
Предлагаю добавить возможность добавлять новые языки в сторонний файл, чтобы легче было редактировать. 
Т.е. набор приветствий должен читаться из файла.

**Comment by fireet** [comment]
добавил функцию чтения из файла, или лучше было оставить код в теле?

**Comment by mgulimonov** [comment]
Когда учишься очень важно понимать почему и что ты делаешь. Попробуй сам ответить на свой вопрос и напиши как лучше сделать и почему?

**Comment by mgulimonov** [comment]
Не забудь ответить на вопрос

**Comment by fireet** [comment]
внес правки.
по вопросу: лучше делать через функцию, так как может потребоваться использовать код повторно, и ошибки искать легче(в конкретной функции, а не во всём коде)
