### ISSUE TITLE
Добавить пулреквест со всеми изменениями, которые нужно проверить.

### ISSUE THREAD

**Issue by mgulimonov** [fireet/hello_world#8]
Без пулреквеста сложно понять общий список изменений которые нужно проверить

**Comment by fireet** [comment]
сдалал новый пул реквест. добавлен модуль добавления языков в файл с словарём(выбранном при старте программы), конечно требуется рефракторинг и ещё подумать)

**Comment by fireet** [comment]
как сделаь хороший декоратор ещё думаю

**Comment by fireet** [comment]
Привет! наконец добрался до плотных занятий.
сделал пулреквест, полностью переписал код... снова
